### ISSUE TITLE
Wrong (or naive) documentation of Drop.send()

### ISSUE THREAD

**Issue by Gottox** [Qabel/qabel-core#165]
```java
    /**
     * Sends the message and waits for acknowledgement.
     * Uses sendAndForget() for now.
     *
     * TODO: implement
     */
```

Drop should not wait until a acknowledge is sent by the receiver. Instead the sender should continue to run and be informed about the acknowledge. there are multiple possibilities how this can be achieved. We should discuss that at the meeting.

**Comment by k-c13** [comment]
Close it because code is merged
