### ISSUE TITLE
Platform indepentent object persistance

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#18]
We need a way to persist object on Android and PC without Android specific code. Maybe @Gottox know more about the persistence possibilities on Android and how this can be done platform independent.

**Comment by thechauffeur** [comment]
We should wait for Qabel/ackack for this.

**Comment by Gottox** [comment]
both, low memory and app close events are not what we want. I think a periodical writeback makes the most sense.

**Comment by thechauffeur** [comment]
I would go for a "on change write" approach.

**Comment by thechauffeur** [comment]
This may be ancient but we still need to solve this to have a BETA core. We almost have everything we need (e.g. (de-)serialization) but need an interface in the core which can write to and read from a persistent storage. The rest must be done in the platform specific repositories.

**Comment by thechauffeur** [comment]
@L-Henke noise is merged. Do you have time for this?

**Comment by L-Henke** [comment]
I do.

**Comment by thechauffeur** [comment]
Please explain your approach. You can additionally make a PR.

**Comment by L-Henke** [comment]
Explanation provided in #316

**Comment by L-Henke** [comment]
We'll introduce a Persistable superclass.
