### ISSUE TITLE
DropController.retrieve() does not work with DropServerURL w/o dropID

### ISSUE THREAD

**Issue by jasinai** [Qabel/qabel-core#182]
In issue qabel/qabel-doc#62 we defined, that the URL of a DropServer should not have a drop id (but the drop id is not cut off). If the DropServer URL is 'wrong', the retrieve method of the DropController does not work.
Shouldn't the DropController have at least 'my' identities with the DropURLs to retrieve the messages?

**Comment by thechauffeur** [comment]
@jasinai please give an update to this issue.
