### ISSUE TITLE
Identify components which are vulnerable to timing attack 

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#21]
Since most of our communication is done asynchronous, only limited parts of the code should be vulnerable to timing attacks. These has to be identified. 

- Re-requests of corrupted communications might be critical
- Drop messages which trigger a further action. (e.g. drop message that notifies about a modified file on the storage system)

**Comment by thechauffeur** [comment]
I will create a PR which incorporates the wiki page into our contribution guidelines and then close this issue.

**Comment by roeslpa** [comment]
@thechauffeur are you okay with it if write it to the guidelines?

**Comment by roeslpa** [comment]
Automatically resolved by #424
