### ISSUE TITLE
Association: StorageServer <-> StorageVolume

### ISSUE THREAD

**Issue by jasinai** [Qabel/qabel-core#232]
According to [Storage Volume Doc](https://github.com/Qabel/qabel-doc/wiki/Qabel-Client-Configuration#storage-volume) there should be an association (the storage_server_id) to [Storage Server](https://github.com/Qabel/qabel-doc/wiki/Qabel-Client-Configuration#storage-server). But the [StorageServer Class](https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/config/StorageServer.java) doesn't have an ID.
Also the StorageServer**s** should have a method to find and get the StorageServer with the given ID.

**Comment by thechauffeur** [comment]
Both Storage Server and Storage Volume do not need an id since both already have an unique identifier (URL and public_identifier). Maybe we will remove these later but for now we keep them because maybe we need them for Qabel Sync.

**Comment by thechauffeur** [comment]
Storage Server and Storage Volume get linked with #241.
