### ISSUE TITLE
Travies: Test errors

### ISSUE THREAD

**Issue by k-c13** [Qabel/qabel-core#246]
Since yesterday the travis test failed with errors:

Here the failed test:
de.qabel.core.http.StorageHTTPTest > deleteStorage
de.qabel.core.http.StorageHTTPTest > uploadToQabelStorageVolume
de.qabel.core.http.StorageHTTPTest > uploadToNotExistingQabelStorageVolume
de.qabel.core.http.StorageHTTPTest > retrieveBlobFromQabelStorageVolume
de.qabel.core.http.StorageHTTPTest > deleteBlobFromStorage

This happened for the following pull requests which does not change anything in storage:
#179 #245

**Comment by jasinai** [comment]
I'm working on a solution. But the problem is in the new version of protocol_update branch in qabel-storage.

**Comment by Gottox** [comment]
Could be an error in some of my fixes. I wasn't sure about some of these changes: https://github.com/Qabel/qabel-storage/commit/bfa3b91ab0d0927a026042d519c4a2106d855bbb

**Comment by k-c13** [comment]
It works again. I can close it. Thanks @jasinai
