### ISSUE TITLE
API for sending a drop message / signing of drop message

### ISSUE THREAD

**Issue by f-porter** [Qabel/qabel-core#247]
I browsed through the test code of the drop component found some things
* first of all I find it really complicated to send a drop message:
I have to instantiate a drop message by my own and set several parameters (of which some don't depend on the senders state, e.g. the timestamp, version, acknowledgeID) before I can finally send it.
Is there a reason why that's not encapsulated somewhere (e.g. DropController)? Or is it just because of the last milestone's urgency?
* Additionally I wonder why the encrypted drop message gets signed with the sign key of the recipient instead of the sender (in class DropController:
```cryptedMessage = encryptDrop(serialize(message),
					contact.getEncryptionPublicKey(),
					contact.getContactOwner().getPrimaryKeyPair().getSignKeyPairs().get(0));```)
Or do I miss something here?
* The same happens when decrypting the message, the private key of a contact is used where the one of an identity should be used.

Edit:
Wait, now I see that the contact owner is used. so forget the last two points ;)

**Comment by aBothe** [comment]
Aren't timestamp, version and ackId initialized to default null/0-values in some of the constructors?
Especially version, which imho is an absolutely internal piece of info that is still handed to the API user.

**Comment by f-porter** [comment]
Yes, you are right. There is a constructor with default values (I was just reading the tests, where this is all set by the caller).
And there is a sendAndForget() method without the need to instantiate a DropMessage before (```sendAndForget(T object, Contact contact)```), but only with one contact as parameter. Maybe there should be a second one for a Collection of contacts and send() methods with the same parameters?

**Comment by aBothe** [comment]
Sounds reasonable to send drop messages to multiple contacts at once.

**Comment by cburkert** [comment]
I'll soon make a PR with a refactored drop API, so keep calm and carry on ;-)
