### ISSUE TITLE
Refactoring TypeAdapter of config classes 

### ISSUE THREAD

**Issue by f-porter** [Qabel/qabel-core#248]
Currently the TypeAdapters return null when the JSON format is invalid. In order to avoid this null returns they have to be changed to throw parsing exceptions.

**Comment by f-porter** [comment]
@cburkert we talked about this last monday:
For properly throwing parsing exceptions I will have to add custom TypeAdapters for every config item and call the TypeAdapter for SyncSettingItem class there. Therefore the SyncSettingItem has to be - despite the documentation - serialized as nested object in the particular item. You were not that happy about using so many custom TypeAdapters, have you found another way to realize that? Otherwise I will go ahead and change the JSON format as described (..and add the necessary TypeAdapters).

**Comment by cburkert** [comment]
@f-porter Unfortunately, I didn't have to investigate this so far. I'd say go ahead with your approach.

**Comment by thechauffeur** [comment]
@cburkert I assigned this to you because at least you talked with @f-porter about this. Please label this (if it makes sense) and set a milestone.

**Comment by cburkert** [comment]
I changed my mind about the urgency of this issue. As long as we are the only ones how create jsons, we can assume the correctness. If we need interoperability we should tackle this issue again.
