### ISSUE TITLE
Port DropController to Ackack

### ISSUE THREAD

**Issue by Gottox** [Qabel/qabel-core#252]
* [x] Make sure all objects which are sent through the Actor are Serializable
* [x] Move DropController to DropActor
* [x] move all calls to the DropController to message passing.

**Comment by Gottox** [comment]
See #272 for the ongoing process

**Comment by Gottox** [comment]
See https://github.com/Qabel/qabel-desktop/pull/6 for the changes in qabel desktop and https://github.com/Qabel/qabel-helloworld-module/pull/3 for those in qabel-helloworld-module

**Comment by thechauffeur** [comment]
Closed by #272
