### ISSUE TITLE
Why doesn't Contact inherit from SyncSettingItem?

### ISSUE THREAD

**Issue by cburkert** [Qabel/qabel-core#265]
While refactoring the drop API, I needed a common class for Contact and Identity to use it as sender in a DropMessage. So I considered introducing an abstract class which both Contact and Identity could be derived from.
But, I noticed that Identity inherits from SyncSettingItem but Contact does not.
Is this right? Should contacts be synchronized, too?

**Comment by aBothe** [comment]
Indeed, seems to be an issue.

**Comment by f-porter** [comment]
you are right. If we want to sync the contacts the same way like the other synced items then it should also inherit from SyncSettingItem. Sure, syncing it the same way would make sense IMO.
But that's not described in the documentation (https://github.com/Qabel/qabel-doc/wiki/Qabel-Client-Configuration#settings) where contacts are also missing in the JSON specified for SyncedSettings.

**Comment by k-c13** [comment]
The reason for that was that contact not really a part of the configuration. So no one add this to that class. 

I update document https://github.com/Qabel/qabel-doc/wiki/Qabel-Client-Contact-Drop-Messages

**Comment by cburkert** [comment]
@k-c13 If contact is not a setting, which I understand, then what do you think about changing the SyncSettingItem to a SyncItem that is semantically not limited to settings or - if we need a Sync**Setting**Item introduce an additional, more general SyncItem?

**Comment by thechauffeur** [comment]
We have two PRs fixing this issue. @cburkert your PR is not linked here. Please discuss which one should be used. Thanks.

**Comment by cburkert** [comment]
My PR #269 introduces a common base class for Contact and Identity which itself inherits from SyncSettingItem, therefore Contact is a SyncSettingItem, too.

**Comment by k-c13** [comment]
> @k-c13 If contact is not a setting, which I understand, then what do
> you think about changing the SyncSettingItem to a SyncItem that is
> semantically not limited to settings or - if we need a SyncSettingItem
> introduce an additional, more general SyncItem?
You are right. You shall change it in your PR

**Comment by cburkert** [comment]
@k-c13 Unfortunately, it is not that easy because Contact and Identity must have the same base class, so I cannot make Contact a SyncItem and Identity a SyncSettingItem. Maybe we can realize the "setting"-property through an interface, but it is too big a change to squash it into my PR #269

**Comment by thechauffeur** [comment]
We do not distinguish between `contact` or `setting`. Technically they are the same for us. #269 does reflect this.

**Comment by thechauffeur** [comment]
This was a discussion so it can be closed before the PR is merged.
