### ISSUE TITLE
Why is ModuleManager.Settings a set of settings, not just a single 'Settings'-instance?

### ISSUE THREAD

**Issue by aBothe** [Qabel/qabel-core#266]
[tl;dr](https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/module/ModuleManager.java#L54)

A Settings-object already contains local&synced settings for all modules,
so why are we making up a further dimension to store multiple sets of module settings?

**Comment by Gottox** [comment]
true, this is a mistake.
