### ISSUE TITLE
Prevent multiple ModuleManagers

### ISSUE THREAD

**Issue by jan-schreib** [Qabel/qabel-core#278]
After reviewing #243 @thechauffeur and I noticed that there is nothing that prevents someone from instanciating the ModuleManager multiple times. We thought about this yesterday and didn't come to a solution. One reason for that was the not finished actor library (we weren't sure if this issue would change when ackack is done).
Of course I can think of multiple ways to prevent multiple ModuleManagers but this needs a bit of thinking from every direction.
I think #185 has something to do with this, too.

**Comment by Gottox** [comment]
Multiple instances of the ModuleManager are malicious. A ModuleManager holds all the classes of modules. Instanciating a new ModuleManager means, that this ModuleManager can't load any new objects.

**Comment by Gottox** [comment]
I'm against a singleton pattern here, as it is very useful for testing purposes to hold multiple instances of a ModuleManager at a time. (only for testing purposes.)

Anyway, the library itself should never instanciate a ModuleManager by itself. It's either the job of the application or of the test.

**Comment by cburkert** [comment]
What's about adding a static getDefaultModuleManager getter to ModuleManager?

**Comment by Gottox** [comment]
True. I used this pattern in the Ackack Eventemitter too.

**Comment by thechauffeur** [comment]
Go ahead.
