### ISSUE TITLE
Unnecessary if statement in cryptoutils.

### ISSUE THREAD

**Issue by jan-schreib** [Qabel/qabel-core#286]
I was reading around and discovered [this](https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/crypto/CryptoUtils.java#L375). 16 - 12 is always > 0 in my world. This if statement can be removed.

**Comment by aBothe** [comment]
Well actually™ it's about handling the case if some developer wants to experiment with these constant sizes. This piece of code is documented and reasoned, so..why remove a check that won't take too long anyway?
[Edit] `new byte[(SYMM_IV_SIZE_BYTE - SYMM_NONCE_SIZE_BYTE)];` .. okay, remove the if, or make it `counter.length() > 0`.

**Comment by L-Henke** [comment]
If someone sets ```SYMM_IV_SIZE_BYTE == SYMM_NONCE_SIZE_BYTE``` the counter shouldn't be set to 1, so this statement is reasoned.

**Comment by jan-schreib** [comment]
Ah, ok I see. Didn't thought about that. Thanks for clarification.
