### ISSUE TITLE
What about letting Sync store module-specific sync info?

### ISSUE THREAD

**Issue by aBothe** [Qabel/qabel-core#288]
I just thought about restricting info access to per-module even further, so it'll be more difficult for third-party-modules to access a module's synced settings without e.g. java reflection:

```
MyData s = syncController.getSyncedData<MyData>();
s.someChatLog += "Me: Lolwut?\n";
syncController.setSyncedData(s);
```
Note that `s` might be a clone of syncController's copy, so there won't be any hassle with version conflicts until setSyncedData() has been called.
Or even better: Encrypt/Decrypt stuff in-memory, although this rather seems like some stuff that could be done post-beta.

**Comment by thechauffeur** [comment]
Wait for #298.

**Comment by thechauffeur** [comment]
Obsolete.
