### ISSUE TITLE
Add the possiblity to use Tor

### ISSUE THREAD

**Issue by schulze** [Qabel/qabel-core#291]
First step in this direction is to use a SOCKS proxy for connections to the internet. A second step would to be resolve names using a SOCKS [proxy extension](https://gitweb.torproject.org/torspec.git/plain/socks-extensions.txt). (See Qabel/qabel-doc/issues/71 for some background.)

**Comment by thechauffeur** [comment]
@jan-schreib you did some research. Please explain.

**Comment by schulze** [comment]
Actually, using the SOCKS extension is not necessary for us, as we don't need to hide that a client connects to a Qabel server. We only need to hide the identity of the user from the server, and hence it is no problem if the user makes DNS requests in the clear.

**Comment by jan-schreib** [comment]
One can use ```java -Dhttps.proxyHost="ip" -Dhttps.proxyPort="port"``` when starting a java application.
