### ISSUE TITLE
Travis CI: Remove IRC notification?

### ISSUE THREAD

**Issue by jasinai** [Qabel/qabel-core#294]
I use travis for my fork and for **every** push to this fork, travis builds it and then notifies the qabel IRC-channel.

Do we really need the IRC notifications? Only 5 people are notified. :wink:
Perhaps it is wise to notify the [author via email](http://docs.travis-ci.com/user/notifications/#Email-notifications) with the default on_success/on_failure settings. (But: "It also prevents build notifications from going to folks not registered on Travis CI.")

**Comment by jan-schreib** [comment]
I don't have an opinion on this, but I don't want emails from travis. For me its enough information to see the colored circle. Do as you like.

**Comment by thechauffeur** [comment]
The notifications for forks can become annoying. If it is not possible to only show notifications for pull requests and / or for builds of the qabel-core branches I opt for this. If not I opt for completely disable IRC notifications.

@Qabel/developer any opinions on this?

**Comment by aBothe** [comment]
Okay, as we're getting merge notification mails anyway, having an irc extra channel isn't that helpful (anymore) -- :+1: for no travis notifications at all anymore.

**Comment by Gottox** [comment]
:+1:

**Comment by cburkert** [comment]
As @jan-schreib said, the visual feedback on the pull request page is all I need. I never used IRC for that.
