### ISSUE TITLE
Log level in DropController retrieve()

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#301]
The ```retrieve()``` method of the DropController uses three different log level for pretty similar error cases. https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/drop/DropController.java#L220-L231

At least the ```info``` and ```warn``` log message should be the same level.

Maybe we should have a little guideline (additional to the log4j documentation) on how to decide the correct log level.

**Comment by thechauffeur** [comment]
These log levels are OK
