### ISSUE TITLE
Java 7 usage of shortened type brackets

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#302]
Although we could use the shortened type brackets from Java 7 e.g. ```ArrayList<Integer> al = new ArrayList<>``` instead of ```ArrayList<Integer> = new ArrayList<Integer>```, we often don't use it. I think we should do this the same way in the code. 
https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/drop/DropController.java#L31

**Comment by thechauffeur** [comment]
Yep, when writing new code / changing old code we should use Java 7 features / syntax.

**Comment by thechauffeur** [comment]
We should add this to our guidelines.
