### ISSUE TITLE
Define how to deal with dependent method calls

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#303]
We sometimes have dependent method calls. (e.g. one method have to be called after another).

E.g: ```registerSender``` has to be called to complete the serialization of a Drop message:
https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/drop/DropMessage.java#L74

And:
The serialize and deserialize of the ```AbstractBinaryDropMessage``` are related to which constructor has been used ```byte[] binaryMessage``` or ```DropMessage<?> dropMessage```. These methods are not testing if the current call is actually possible.

How should be deal with that kind of dependent methods. Is a Javadoc comment enough, or is there maybe a better way to do this? Should these methods check if their call is valid in the current context?

**Comment by L-Henke** [comment]
#316 has a dependent method call. The Persistence class can be only used after ```init("password")``` has been called. All methods are checking if ```init``` has been called and will throw an ```IllegalStateException``` with an explanation why this call has failed if ```init``` hasn't been called before. 

I think this is how we should deal with dependent method calls. This is a lot better than checking why an unspecified error has occurred. 

@Qabel/developer please let me know if you can approve this concept as our general approach.

**Comment by cburkert** [comment]
Sounds valid to me.

**Comment by L-Henke** [comment]
We want to have this concept and will document it.
