### ISSUE TITLE
Compile curve25519 lib with gradle or provide binaries for all supported operating systems

### ISSUE THREAD

**Issue by jan-schreib** [Qabel/qabel-core#307]
It would be nice to have an extra option to recompile the shared library for the jni component.

**Comment by thechauffeur** [comment]
@moritz4004 ask @jan-schreib if you need help.

**Comment by jan-schreib** [comment]
@moritz4004 whats the status on this?

**Comment by moritz4004** [comment]
I have created a pull request. There is an Error, if you try gradle build in Qable Core.

**Comment by thechauffeur** [comment]
Just as a side note. If this will not work in a timely manner we can provide binaries for the other operating systems. So this is really an enhancement.

**Comment by thechauffeur** [comment]
I changed the meaning of this issue a little bit because we need to address this until a BETA release and not after that.

**Comment by thechauffeur** [comment]
@hartmannaf please ask @moritz4004 what is going ob with this and tell me or update this issue (and assign yourself).

**Comment by cburkert** [comment]
@moritz4004 Now that you're back, please re-tackle this issue.

**Comment by jasinai** [comment]
I think, this issue is closed by Qabel/qabel-core#407, or is there more to do?

**Comment by jan-schreib** [comment]
We are not able to build for the Apple operating system right now, we could however close this one and open another for just the Apple part.

**Comment by audax** [comment]
And I just did exactly that.
