### ISSUE TITLE
Travis fails due to silenced output

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#308]
Since our tests are running very long and all servers output has been silenced with #306, Travis assumes that the build process has failed and terminates it:

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

What can we do to avoid this without having all that messy server outputs?

**Comment by jan-schreib** [comment]
As a workaround we could add echo statements before and after each server start.

**Comment by Gottox** [comment]
Just silence the servers, not npm and pip.

**Comment by L-Henke** [comment]
Would this problem also occur if our tests are running for more than 10 minutes?

**Comment by jan-schreib** [comment]
Let's try.

**Comment by jan-schreib** [comment]
Let's keep this issue open until we do not notice timeouts any more.

**Comment by thechauffeur** [comment]
11 days w/o any timeouts. I think we can close this. Reopen if needed.
