### ISSUE TITLE
Why not have an extra enc/sign key for each contact?

### ISSUE THREAD

**Issue by aBothe** [Qabel/qabel-core#310]
Instead of maintaining a single key per Identity, why not choose to take one private key that is exclusively used for communication with one contact?

This way, in the case of data abuse/leakage/whatever, a untrustworthy/breached contact may can't use his public keys to derive any relationship info when comparing keys with other clients' data.
https://github.com/Qabel/qabel.github.io/blob/master/_docs/Threat-Model.md#contacts might be solved then.

**Comment by aBothe** [comment]
This could btw mean that an Identity does not longer need any general enc/sign key.

For Storage, each QSV could have its own key as well (if that's not the case already).

**Comment by jan-schreib** [comment]
Think about the dead drop messages. I would have to test every key I have. Think about 300 keys, 300 times trying to decrypt a message and so on... This would probably kill every mobile phone batterie.

**Comment by aBothe** [comment]
Plausible argument. Could it still be (made) an option for stationary hardware clients or paranoid users?

**Comment by L-Henke** [comment]
The other thing is, sometimes you want to have a single key for an identity. Like when you want to print your key on a business card.

**Comment by aBothe** [comment]
Not sure if that's a weighy argument though^^

**Comment by L-Henke** [comment]
It is, because your proposal would completely change the **whole** concept, unless you come up with a better key exchange/validation idea.

**Comment by aBothe** [comment]
Just thought about that QR validation method via smartphones.
And since those contacts are usually kept synced with any of the user's desktop clients, the validation would work indirectly for stationary clients as well.
But okay, perhaps there was a discussion about this before and I likely missed it.

**Comment by cburkert** [comment]
Another disadvantage of contact-individual keys is that transitive trust models will no longer work.
Furthermore, these individual keys may even impose a privacy issue, because public keys (and their distribution) now tell an even more detailed story about social networks.

**Comment by aBothe** [comment]
Good point.
