### ISSUE TITLE
Error while local build after Qabel Noise merge

### ISSUE THREAD

**Issue by f-porter** [Qabel/qabel-core#311]
Some of the Unit tests are failing with the error:
java.lang.NoClassDefFoundError: Could not initialize class de.qabel.core.crypto.Curve25519

Does anyone knows how to solve that?

**Comment by L-Henke** [comment]
Currently the provided ```.so``` is only available for Linux x86_64.

**Comment by f-porter** [comment]
Yes, I am running Debian on 64bit. So that should work, shouldn't it?

**Comment by L-Henke** [comment]
The ```libcurve25519.so``` has to be in the root directory of your project. If your are using the qabel-core repo, everything should work. If you are already using the qabel (meta) repo, you should copy the ```libcurve25519.so``` from the qabel-core directory to the qabel directory. We'll come up with a real solution later.

**Comment by f-porter** [comment]
Okay, but i am using the qabel-core repo as well.

**Comment by f-porter** [comment]
I think that problem somehow is related to Eclipse. As workaround I copied the ```libcurve25519.so``` to ```usr/lib/jni``` which is part of the ```java.library.path```. For now that works.
Thanks for your replies, I wasn't sure if I was missing something obvious.
