### ISSUE TITLE
Fix liveCycleTest

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#319]
```liveCycleTest``` randomly fails in Travis. This false positive has to be fixed.

Edit: Further the name probably should be li**f**eCycleTest.

**Comment by L-Henke** [comment]
Maybe a race condition.

**Comment by jasinai** [comment]
In #339 we will ignore the test for now, so that we will have no randomly failing tests.
We have to look into this, if the lifeCycle is testable.

**Comment by thechauffeur** [comment]
This is not so time-critical but let us all keep an eye on this.

@jasinai and @L-Henke you did some research here. Please give an update if you have something.

**Comment by thechauffeur** [comment]
@L-Henke was the commit which closed this part of a PR from you? If so should this issue be closed or not?

**Comment by L-Henke** [comment]
I have done nothing that would fix that test and it is still ignored.

**Comment by jan-schreib** [comment]
I just unignored this test and pushed it into the wrong repo by accident. Travis did not fail - fixed by accident?

**Comment by audax** [comment]
Well...it randomly fails, so we don't know if it actually is fixed or if it was just "luck".
