### ISSUE TITLE
public retrieving of an ContactsActor instance

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-core#333]
In #332 the method for retrieving an instance of `ContactsActor` public. Without this fix the qabel-desktop component cannot build because it calls this method and is not a member of the `config` package.

If making it only available package wide is intended for good reasons we have to change it. @L-Henke please investigate this. This issue may only be an enhancement -- if so please update it.

**Comment by L-Henke** [comment]
I have done the same in #329, so I think this should be fine.
