### ISSUE TITLE
Merge ConfigActor and ContactsActor into ResourceActor

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-core#335]
@L-Henke wrote in #330 
> Since the ConfigActor and the ContactsActor are very similar, I think it would be easier for a developer to provide the config values (like identities, drop server, etc) and the contacts by the same actor.

@f-porter and I agree that this might be a good idea.

#330 is closed and will be redone later. This issue is a reminder for that.

**Comment by L-Henke** [comment]
Closed by #355
