### ISSUE TITLE
Change URL to URI

### ISSUE THREAD

**Issue by jasinai** [Qabel/qabel-core#340]
We use URL in several classes, but this brings problems with it.
Comparing two urls:
- makes a DNS lookup, which can be a blocking operation
- they are equal, if they have the same IP address

I think, we should change it from URL to URI.

**Comment by aBothe** [comment]
:+1: We definitely should go for that - although there also could be URNs (`a:b:c`) specified, despite I doubt that users will ever figure out. :stuck_out_tongue:

**Comment by thechauffeur** [comment]
@jasinai when you are ready with the Travis / meta repository issues you can look into this. Try to find out first if this is just a code refactoring (if so just create a PR) or if this has to be discussed because it will change a lot.
