### ISSUE TITLE
Define default LocalSettings

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#343]
The constructor of LocalSettings currently takes two arguments: ```long pollInterval, Date dropLastUpdate``` which are currently not used for anything. In #329 I was required to instantiate the LocalSettings, so I just set these values to something just to be able to use the object. We need to define if these settings are required in the constructor and how they should be set later. The code line is currently marked with a TODO comment.

**Comment by thechauffeur** [comment]
Let's not make a big deal out of this and just set them to some not totally dump default value. It is more important that these defaults can be changed easily.

@L-Henke is this the answer you needed to close this issue or do we have to actually patch the code to be able to set default values for our settings?

**Comment by L-Henke** [comment]
Default values are set and a TODO comment is in the code. Issue will be handled later.
