### ISSUE TITLE
Define what events should get emitted by the Config/ContactsActor

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#344]
Currently almost all events except changed LocalModuleSettings are emitted on the EventEmitter. We have to think about what events really have to be emmited.

**Comment by thechauffeur** [comment]
@L-Henke please label this issue and maybe set a milestone. If you do not actively do anything on this issue you can deassign yourself after that.

**Comment by thechauffeur** [comment]
Related to #348

**Comment by audax** [comment]
We don't use the actors anymore, ackack will be removed in the future and is not used in the desktop and android projects.
