### ISSUE TITLE
Register module settings

### ISSUE THREAD

**Issue by cburkert** [Qabel/qabel-core#348]
Modules need to register their synced and local module settings either via direct communication with the ConfigActor or through the ModuleManager. For the latter, the Module API needs getters and setters for these module settings classes.

@L-Henke and I will work on that after latest changes on the ModuleManager are upstream.

**Comment by thechauffeur** [comment]
I think this is an important issue to properly use a module. Use `qabel-helloworld` and add a setting to this module to try this.
