### ISSUE TITLE
Module class needs extensive documentation

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-core#352]
E.g. the fact that the `onEvent` method will be called from another thread must be clear.

**Comment by L-Henke** [comment]
#349 added descriptions to ```Module``` and ```ModuleManager``` but someone else have to decide if it is extensive enough. @Qabel/developer please check if you can understand it.

**Comment by thechauffeur** [comment]
I will read the provided documentation and update (hopefully close) this issue after that.

**Comment by thechauffeur** [comment]
This issue is deprecated.
