### ISSUE TITLE
Adapt changes in android-workaround branch to master

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-core#361]
In a nice way for the reviewers :)

**Comment by L-Henke** [comment]
For now these are:
https://github.com/Qabel/qabel-core/pull/367
https://github.com/Qabel/qabel-core/pull/368
https://github.com/Qabel/qabel-core/pull/369
https://github.com/Qabel/qabel-core/pull/370
https://github.com/Qabel/qabel-core/pull/371
https://github.com/Qabel/qabel-core/pull/372

**Comment by thechauffeur** [comment]
@L-Henke I don't know if this issue still makes sense now. Do as you wish.

**Comment by L-Henke** [comment]
Obsolete. Everything is merged.
