### ISSUE TITLE
We should use the new Travis container-based infrastructure

### ISSUE THREAD

**Issue by jasinai** [Qabel/qabel-core#365]
Travis is notifying during builds: `This job ran on our legacy infrastructure. Please read our docs on how to upgrade`
The [upgrade guide](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade) says:
* Builds start in seconds
* Faster builds
* Caching available for open source projects
* etc.

**Comment by thechauffeur** [comment]
Sounds good, go ahead :+1:
