### ISSUE TITLE
Remove unnecessary branches

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#373]
There are a lot of branches that seem unnecessary to me like, "silence", "unsilence-install", etc. 
I think someone should remove those.

**Comment by jasinai** [comment]
Yes, the `silence`, `unsilence-install` and `irc-notifications` are already merged. I will delete them.
What is with the `android-workaround` branch? Can we remove it, after your PRs are merged?

**Comment by L-Henke** [comment]
Yes. That won't be needed anymore.

**Comment by jan-schreib** [comment]
@jasinai This is done, right? Go ahead an close the issue if so.
