### ISSUE TITLE
Unhandled exception with unregistered DropMessage

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#374]
If a DropMessage is deserialized with an unknown class (e.g. because currently no module is loaded that uses this class) the core crashes.

This is because the DropDeserializer thows an [exception](https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/drop/DropDeserializer.java#L38) which is not handled by the [caller](https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/crypto/AbstractBinaryDropMessage.java#L125).

Since it can be possible, that a DropMessage is decrypted without any module is registered to that object, this case has to be handled without a crash.

**Comment by jan-schreib** [comment]
@L-Henke Isn't this closed by #376 ?

**Comment by L-Henke** [comment]
Right, this should be fixed by #376, although it was not the main purpose of that PR.
