### ISSUE TITLE
Can't add the same Contact twice (e.g. for different Identities)

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel-core#384]
Since the ```EntityMap``` stores entities in a ```HashMap``` with the ```KeyIdentifier``` as the key and the ```ResourceActor``` uses one ```EntityMap<Contact>``` to store entities, it is impossible to add two entities with the same ```KeyIdentifier```. This would be needed if two or more ```Identities``` would try to add the same ```Contact```.

See: https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/config/EntityMap.java#L32

**Comment by audax** [comment]
We could circumvent this in the android application by not using the Contacts-entity map. Should we do this or change the core?

@Qabel/developer

**Comment by thechauffeur** [comment]
@jmt85 discuss this with @julianseeger, @L-Henke and @audax and decide as you wish.

**Comment by julianseeger** [comment]
What's the usecase for the EntityMap on Android?
Use one EntityMap per Identity and you're fine. The qabel-desktop doesn't use EntityMaps at all because we don't have a usecase for it yet.

**Comment by L-Henke** [comment]
There is no "Android use case". The EntityMap was used by the ResourceActor which was the ackack way of managing resources. Since the Android project doesn't use ackack any more, we might have a workaround in Android. But if the ResourceActor will stay in the qabel-core (which I honestly don't know), this issue should be fixed in the core. If we are going to remove ackack anyway, this could be fixed in the refactorization process.

**Comment by L-Henke** [comment]
But we are still using the ```Identitites``` class which is a child class of EntityMap. So we should still have these issues. Of course we could simply switch to a simple Set or Map.

**Comment by julianseeger** [comment]
Ok, now I got it. `EntityMap` is totally fine but the ResourceActor doesn't catch the concept of separate contacts per identity.
Then I'm trying to remove the `ResourceActor` and as much of ackack as possible with this issue (probably preferable over fixing the ResourceActors concept).

>But we are still using the Identitites class which is a child class of EntityMap. So we should still have these issues. Of course we could simply switch to a simple Set or Map.

Multiple Identities with the same key ... srsly? This would break a lot of code I've seen so far, not only the ResourceActor

**Comment by L-Henke** [comment]
Of course not multiple identities with the same key. I just wanted to state, that we are using the different derived classes from EntityMap, but this issue is of course not present with Identities.
