### ISSUE TITLE
Travis does not have Python3.4 for qabel-drop and qabel-accounting

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-core#386]
Travis does not allow multiple language entries, so we are stuck with either a free choice of JDKs or a free choice of Python versions.

If we do not specify `language: java`, we only have access to oraclejdk7. If we do not specify `language: python`, we only have access to Python 2.7 and Python 3.2.

Either we use Python3.2 for qabel-drop and qabel-accounting, which may be problematic because many libraries only support 3.3+, or we change the travis language to java and only test on oraclejdk7.

Other options:
* Switch to another CI, like for example Jenkins or drone.io which are much more flexible
* Switch back to the legacy infrastructure on travis which allows the use of sudo. With sudo we can grab Python3.4 from a PPA and install it directly.
* Switch back to the legacy infrastructure on travis and use docker containers to run qabel-drop,storage and accounting
* Run the tests with language:python and therefore only with oraclejdk7 until travis finally upgrades their containers to Ubuntu 14.04

**Comment by jan-schreib** [comment]
I don't really haveopinion on this, but I strongly advise to stay in the cloud when switching our CI-System.
@Qabel/developer whats your opinion on this?

**Comment by L-Henke** [comment]
Testing other JDKs is not that necessary, since we even allow them to fail. So only testing oraclejdk7 should be feasible and a very quick solution compared to setting up a new test infrastructure.

**Comment by jan-schreib** [comment]
Java 7 is also the Android version, isn't it?

**Comment by L-Henke** [comment]
Yes. Java 8 is currently not supported on Android.
