### ISSUE TITLE
Create and list prefixes

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-core#391]
Implement this interface: https://github.com/Qabel/qabel-accounting/issues/23

See #388

**Comment by thechauffeur** [comment]
@audax IIRC you want to references useful stuff for @roeslpa here.

**Comment by audax** [comment]
See the PR at #388 for how the accounting interface is implemented. @roeslpa

**Comment by roeslpa** [comment]
Is there a specific reason why quota in AccountingProfile is an Integer and not an int?

**Comment by audax** [comment]
No, no specific reason and you may change it.

**Comment by audax** [comment]
The PR for the server side is merged: https://github.com/Qabel/qabel-accounting/pull/24
