### ISSUE TITLE
Create and update directory metadata files

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-core#394]
Implement the SQLite schema described in the spec.

Methods:

DirectoryMetadata(SQLiteConnection)

commit() which bumps the version and flushes

insertFile(BoxFile)
updateFile(BoxFile)
deleteFile(BoxFile)
BoxFile[] listFiles()

insertFolder(BoxFolder)
updateFolder(BoxFolder)
deleteFolder(BoxFolder)
BoxFolder[] listFolders()

insertExternal(BoxExternal)
updateExternal(BoxExternal)
deleteExternal(BoxExternal)
BoxExternal[] listExternals()

Only in a subclass IndexMetadata:
insertShare(BoxShare)
updateShare(BoxShare)
deleteShare(BoxShare)
BoxShare[] listShares()

Attributes:

* root
* name
* version
* last_change_by

**Comment by roeslpa** [comment]
I guess this issue was solved by #403?

**Comment by audax** [comment]
yup.
