### ISSUE TITLE
Input validation in the core

### ISSUE THREAD

**Issue by jan-schreib** [Qabel/qabel-core#436]
I have some concerns about not checking input data in the core.
It's too easy to forget checks that have to be done in the frontend.

I discussed that a bit with @audax and we have different point of views on this.
Maybe some others have also an idea or best practice experience on topics like this.

The issue for raising the question on my site was: https://github.com/Qabel/qabel-core/pull/431

**Comment by thechauffeur** [comment]
We do not need to address this.
