### ISSUE TITLE
Doku-change "drops" to "dropUrls" 

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-core#438]
Qabel doku is not up-to-date with the code.

Please change "drops" into "dropUrls" at Identity

http://qabel.github.io/docs/Qabel-Client-Configuration/

**Comment by thechauffeur** [comment]
It must be updated in the documentation.

**Comment by roeslpa** [comment]
Resolved by https://github.com/Qabel/qabel.github.io/pull/134
