### ISSUE TITLE
make entities and entitysets observable

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-core#456]
As neither Contact, nor Identity is an interface, you cannot wrap them to observe state changes. Because it is neccessary to do so, both Contact and Identity (and also Contacts and Identities) should be observable and notify about changes in all mutable properties.

PS: doesn't matter if it they really extend `Observable` or have some lightweight implementation like `onChange(Runnable handler)` which can be called with `identity.onChange(avatar::update)` fe

**Comment by audax** [comment]
This very old "time-critical" issue is now deprecated imho. We use the event system for stuff like that and not observable repositories or collections.

**Comment by julianseeger** [comment]
jop
