### ISSUE TITLE
Make lastModified available in HTTPResult

### ISSUE THREAD

**Issue by wischweh** [Qabel/qabel-core#471]
In order to be able to make use of the lastModifiedSince feature in the clients we need the serverTime for the result included in the HTTPResult. cf https://github.com/Qabel/qabel-android/issues/272 android/issues/272 and https://github.com/Qabel/qabel-desktop/issues/154

we need a fiel like long lastModifiedSince in HTTPResult to be able to implement this, which should be set by DropHTTP.

**Comment by julianseeger** [comment]
Did you check if the response from the server contains a date?
When I created Qabel/qabel-desktop#154 there was one ;) And since between the last modification and "now", no new message was received should be as good as a last-modified header.

**Comment by julianseeger** [comment]
depends on https://github.com/Qabel/qabel-drop/pull/44
