### ISSUE TITLE
Block server must check etag befor overwriting

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-core#491]
Before the block server overwrites a file it must verify the etag, if it is the same file

**Comment by audax** [comment]
I think this should be in the block server repository, shouldn't it? @jmt85

**Comment by jmt85** [comment]
yes

**Comment by jmt85** [comment]
Issue moved to [Qabel/qabel-block #44](https://github.com/Qabel/qabel-block/issues/44) via [**ZenHub.io**](https://www.zenhub.io/)
