### ISSUE TITLE
c_time vs m_time vs checksum

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-core#493]
m_time → ux → important
  Folders don’t have m_times

current state
m_time
Desktop → get time from client
Android → gets time from server

in the dm the c_time replace due hashes

**Comment by julianseeger** [comment]
So what's exactly to do here?
https://github.com/Qabel/qabel-core/issues/492 references hashes for files. So is this the "store filehashes in dm" ticket and #492 is the "ensure that directories with the same content do not conflict" ticket?

**Comment by audax** [comment]
This is for storing hashes for files in the DM.
