### ISSUE TITLE
"Hello" Protokoll

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-core#495]
The following information is to be appended to each message Drop → piggyback

- Drop Url
- Pub Key
- Alias

The following information should be appended with only "known" contacts

- E-Mail → not unique 
- phone number → not unique

**Comment by JoGir** [comment]
ups #537 resolves this

**Comment by jmt85** [comment]
np ;)

**Comment by audax** [comment]
Already merged, just needs the client implementation now.
