### ISSUE TITLE
cross client sync 

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-core#496]
The Qabel core includes the main logic for the cross client sync. Every update of the a contact is a separate transaction. 

The core must also have the ability to solve conflicts (example via Rollbacks)

**Comment by julianseeger** [comment]
Do we need to split the transaction files into separate directories? (For example per contact? Otherwise we would get a lot of changeset-files in a single directory)

**Comment by julianseeger** [comment]
New approach for "special" files and folders:
we create a new prefix with a new indexDM and add all "special" stuff to that volume.

This way we don't need any special treatment for these files and they never appear in a filebrowser or folder sync.

**Comment by audax** [comment]
If we use `SHA256(prefix + private_key +1)` for the adress of it, we won't get conflicts with box-index dms.
