### ISSUE TITLE
refactoring abstract navigation

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-core#502]
For the writable shares the abstract navigation must be improved

**Comment by julianseeger** [comment]
I'm using this ticket to refactor out the common parts of the AbstractNavigation (and other box classes) from both clients to pull a basic qabel box module to the core

**Comment by julianseeger** [comment]
https://github.com/Qabel/qabel-android/issues/543 is a child-issue of this

**Comment by julianseeger** [comment]
ftr.: if the android-project succeeds to integrate the box-component (core repo), we have a lot of code in common. Even the concrete implementations of Navigation are included.
