### ISSUE TITLE
sharing sender doesn't keep the shares

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-core#543]
the indexDM is currently not handled correctly. For example when sharing a file (from a submfolder), the indexDM is changed but not uploaded => the share that has been added to the list of shares in the indexDM is never uploaded.

**Comment by audax** [comment]
Relevant for https://github.com/Qabel/qabel-android/issues/562

**Comment by audax** [comment]
Reproducable with autocommit disabled
