### ISSUE TITLE
InMemoryContactRepository always deletes contact

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-core#580]
The sql repository only deletes the contact if it is not attached to any identity, the in memory one always deletes the contact.

**Comment by julianseeger** [comment]
It's a testdouble. Just adjust it if you have a test that would like to use the InMemoryContactRepository but needs that behavior

**Comment by audax** [comment]
and this ticket is a reminder to update the testdouble and use it in the test instead of the sqlite repository:
https://github.com/Qabel/qabel-android/pull/642/files#diff-e7e578abf1a49b36a2aa8d2616f8cb03R156

This difference in behavior caused a bug in the android client, which is I wanted to point it out.
