### ISSUE TITLE
Deleted file doesn't vanish from the file browser.

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-core#622]
@jan-schreib commented on [Wed Sep 28 2016](https://github.com/Qabel/qabel-android/issues/688)

To reproduce:
Upload a file.
Share the file.
Look at it in the filebrowser.
Delete the file.

File does not vanish from the browser.
Restarting the application doesn't help.

---

@audax commented on [Wed Sep 28 2016](https://github.com/Qabel/qabel-android/issues/688#issuecomment-250178299)

Does this happen with files that are _not_ shared, or only with files that are shared?

**Comment by audax** [comment]
Shared files need to be "double deleted". The rest of the bug was a caching issue.

**Comment by thechauffeur** [comment]
With the current released version (`10.0.2`) I cannot reproduce the workaround mentioned above.

- I shared a file (let's call it `foo`) which was already there in the file browser (fb)
- I tried to delete foo afterwards while it was shared (text under foo in fb also stated it is shared with $contact-name-I-shared-foo-with)
- There is a popup saying "no file named foo".
- I try to delete it again.
- Same error message.
- foo is still there.
- I unshare foo.
- //jump mark A.
- Try to delete foo.
- foo is still there.
- repeat A for >>2 times.
- //jump mark B.
- I try to delete another file which was already there in fb (let's call it `bar`) which is not shared.
- bar is still there.
- repeat B until >>2 times.
- I upload a new file (let's call it `baz`).
- //jump mark C.
- I try to delete baz.
- baz is still there.
- repeat C for 3 times.
- killed the app (using android app overview -> gesture to close an app).
- start app again.
- repeat C for 1 time.
- baz is still there.
- I can still open and see foo, bar and baz (these files are pictures).

Conclusion. I cannot delete any files.

**Comment by thechauffeur** [comment]
Addition: I used our fairphone 2 test device. All the files reside in the same subfolder.

**Comment by thechauffeur** [comment]
It is working in the root folder.

**Comment by thechauffeur** [comment]
@JoGir stated in Qabel/qabel-android#727 that his PR resolves this issue here but he accidentally referenced Qabel/qabel-android#622 instead of this here because this issue here resides in the core repository and his PR introduced changes inside the android repository.

So my question is if this issue here is resolved now and if so please explain why a core issue can be resolved with changes in the android repository.

**Comment by julianseeger** [comment]
Mysterious thing. This issue should probably have been created in the qabel-android project (as everyone seems to assume this can be reproduced on android ^^).

**Comment by julianseeger** [comment]
>So my question is if this issue here is resolved now

@audax should know why he moved this issue from android. Maybe he thought it would be a bug in the core. It was actually a bug in android that prevented deletes in subfolders.

>and if so please explain why a core issue can be resolved with changes in the android repository.

So no bug in the core had to be resolved ... that's the answer then.

**Comment by audax** [comment]
There was a bug in the core which prevent deleting shared files with a single delete call. This issue here is not about files in subfolders.

The issue however was resolved, I cannot reproduce it anymore with core version 0.25.7.
