### ISSUE TITLE
Timestamps in chat are time of download

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-core#625]
This is confusing as not all clients are always on and always receiving drop messages.

E.g. the time when the server received the message is preferable.

A workaround would be to let the clients state "received a moment ago" instead of "a moment ago" to clarify the confusion but it would be better to have more meaningful timestamps.

**Comment by audax** [comment]
I don't think it works this way: 
https://github.com/Qabel/qabel-core/blob/master/chat/src/main/java/de/qabel/chat/service/MainChatService.kt#L161

The time shown is the creation date of the drop message, thus it depends on the correctness of the senders clock.

**Comment by audax** [comment]
I don't think it works this way: 
https://github.com/Qabel/qabel-core/blob/master/chat/src/main/java/de/qabel/chat/service/MainChatService.kt#L161

The time shown is the creation date of the drop message, thus it depends on the correctness of the senders clock.

**Comment by julianseeger** [comment]
It's a bug in the desktop. The [code bridge in the DropDaemon](https://github.com/Qabel/qabel-desktop/blob/master/src/main/java/de/qabel/desktop/daemon/drop/DropDaemon.java#L63) doesn't keep the creationDate. Thus, the default `new Date()` is used [here](https://github.com/Qabel/qabel-core/blob/master/core/src/main/java/de/qabel/core/drop/DropMessage.java#L38)

**Comment by julianseeger** [comment]
Issue moved to [Qabel/qabel-desktop #536](https://github.com/Qabel/qabel-desktop/issues/536) via [**ZenHub**](https://www.zenhub.com/)
