### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [Qabel/qabel-core#673]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by audax** [comment]
I tried the framework, but it doesn't work on android, because `java.lang.instrument.ClassFileTransformer ` is missing. Are you planning to support android?

**Comment by oleksiyp** [comment]
No, android device tests are not supported unfortunately. I have it in backlog, but seems it is pretty advanced topic

**Comment by audax** [comment]
If you ever support Android, feel free to contact me again. Your library has a nice interface and I would like to use it.
