### ISSUE TITLE
Model Classes must be registered

### ISSUE THREAD

**Issue by Gottox** [Qabel/qabel-core#68]
To prevent code injections, prior to dynamical instatiations of Model Classes, Modules must register the Model Classes they use.

this may be done in the init method of a module.

**Comment by k-c13** [comment]
@Gottox and I check the code and find out that in the moment nothing is todo. I will create a getter function for the class loader

**Comment by Gottox** [comment]
We are using a dedicated ClassLoader for Classes. This classloader contains only classes from Module Jars. We assume, that we can trust qabel modules.

For an android port we need a refactoring at this point, but I think it's best if we delay this when we port it over.

**Comment by jan-schreib** [comment]
This needs further discussion because #243 is so horribly broken.

**Comment by thechauffeur** [comment]
Does #243 even has something to do with this issue?

**Comment by thechauffeur** [comment]
According to  @Gottox this is obsolete but he wants to keep this open to further think about it.

**Comment by thechauffeur** [comment]
@L-Henke do what you want with this. It is definitely not needed for the first release (as you can see from the label and the milestone).
