### ISSUE TITLE
Detail handling of module settings 

### ISSUE THREAD

**Issue by cburkert** [Qabel/qabel-core#91]
Reviewing the settings concept, I noticed, that the *ModuleSettings classes contain no information as to which module they belong to.
This is currently missing, isn't it?

@Gottox Can you explain your idea behind the module settings handling?

Shouldn't there be a module identifier member in the AbstractModuleSettings class or something like this?

**Comment by thechauffeur** [comment]
@cburkert with is ancient. Close this if not needed anymore.

**Comment by cburkert** [comment]
I think this issue is still unresolved, because the type adapter for abstract module settings is still missing. @Gottox you started the todo list above. Am I right?
There is also a todo comment in the SyncSettingsTypeAdapter.

**Comment by thechauffeur** [comment]
@cburkert you looked into this. Please make a PR and let @f-porter review it.

**Comment by thechauffeur** [comment]
BUMP.

@cburkert what is the status of this issue? If you did something about this (e.g. a PR) it is not mentioned here.

**Comment by cburkert** [comment]
Almost finished. I have to polish up the code, write same tests and that's it. Stay tuned.
