### ISSUE TITLE
Zip/compress JSONs before encrypting/sending them

### ISSUE THREAD

**Issue by aBothe** [Qabel/qabel-core#92]
This might reduce the time/bandwidth needed to encrypt or send all the data - but will obviously take some time to actually compress the strings + drop queries probably have a very small mem footprint anyway, so the zip's dictionary would only create overhead then.

Might be good to have some benchmarks or a rough estimation whether this is actually needed concerning the quota between encryption time vs. compression time.

**Comment by thechauffeur** [comment]
As we just discussed you want to look into this @L-Henke and @cburkert.

**Comment by cburkert** [comment]
The compression is definitely threatens the confidentiality. But the variable drop message sizes are also an issue concerning meta data avoidance. I opened a new issue Qabel/qabel-doc#81 to discuss padding of drop messages.
Without padding, compression must not happen.

**Comment by roeslpa** [comment]
We decided to pad so the only reason to compress would be the payload being >2KB. Do we want to compress, forbid or split in this case? Or should this stay an enhancement issue until we have enough time?

**Comment by aBothe** [comment]
Let's split it them instantly instead of looking at the compressed size - this results in an easier algorithm and creates fewer headaches in the future.
We shall not zip!

**Comment by cburkert** [comment]
I'm also against splitting on this level. If any, it should be up to the drop user (module) to split messages. Transparent splitting by the drop controller would also require reassembling on this level and thus would require the introduction of segment numbers and all that stuff. I mean IPv6 got rid of segmentation with good reason.

**Comment by roeslpa** [comment]
So as @cburkert, @aBothe and I wrote, we do not want to compress drop messages. Reasons can be seen above. Splitting seems to be a bad idea as well, so drop messages are limited to the length of 2KB (for now).
