### ISSUE TITLE
Are QSVs untouchable while being (over)written?

### ISSUE THREAD

**Issue by aBothe** [Qabel/qabel-core#93]
Just thought about this question concerning possible race conditions for the sync component.

When uploading stuff into a QSV, will the server ensure that noone else/no other client etc can neither read nor write into the same QSV?
Perhaps it should be possible that a QSV may be readable while being written - but then the read procedure takes as long as the data is loaded up OR it just dumps an old version of the QSV's contents.

**Comment by audax** [comment]
Storage is being redone anyway.
